spring.config.import=optional:file:.env

# ===============================
# APPLICATION
# ===============================
spring.application.name=${SPRING_APPLICATION_NAME:FixOnGoBackend}

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.name=${SPRING_DATASOURCE_NAME:CollegeData}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3307/FixOnGoDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# ===============================
# SPRING SECURITY
# ===============================
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:admin123}
spring.security.user.roles=${SPRING_SECURITY_USER_ROLES:ADMIN}

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=DEBUG

# ===============================
# EMAIL CONFIG
# ===============================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:fixongofficial@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:itoi hivi njsb gzfy}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED:true}

# ===============================
# FILE UPLOAD CONFIG
# ===============================
spring.servlet.multipart.enabled=${SPRING_SERVLET_MULTIPART_ENABLED:true}
spring.servlet.multipart.file-size-threshold=${SPRING_SERVLET_MULTIPART_FILE_SIZE_THRESHOLD:2MB}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:2MB}

# ===============================
# SERVER PORT (IMPORTANT FOR DEPLOY)
# ===============================
server.port=${PORT:8080}